[Variables]
CmLs.ToDoList\8.CMCommon.T01=#Tm.Skin_Settings#
CmLs.ToDoList\8.CMCommon.T02=#Tm.Manage_Project#
CmLs.ToDoList\8.CMCommon.T03=-
CmLs.ToDoList\8.CMCommon.T04=#Tm.Help#
CmLs.ToDoList\8.CMCommon.T05=-
CmLs.ToDoList\8.CMCommon.T06=#Tm.Variants#
CmLs.ToDoList\8.CMCommon.T07=#Tm.Refresh#
CmLs.ToDoList\8.CMCommon.T08=#Tm.Unload#
CmLs.ToDoList\8.CMCommon.T09=#Tm.More#
CmLs.ToDoList\8.CMCommon.T10=

CmLs.ToDoList\8.CMCommon.A01=#Ac.Skin_Settings#
CmLs.ToDoList\8.CMCommon.A02=#Ac.Manage_Project#
CmLs.ToDoList\8.CMCommon.A03=[]
CmLs.ToDoList\8.CMCommon.A04=["https://github.com/stevehsudrawing/quantoflx/wiki/Manual-of-''Quanto-Flx-Gadgets''-Package#to-do-list"]
CmLs.ToDoList\8.CMCommon.A05=[]
CmLs.ToDoList\8.CMCommon.A06=#Ac.Variants#
CmLs.ToDoList\8.CMCommon.A07=[!WriteKeyValue "Variables" "PrvIndex" "0" "#CURRENTSKINSETTINGS#"]#Ac.Refresh#
CmLs.ToDoList\8.CMCommon.A08=#Ac.Unload#
CmLs.ToDoList\8.CMCommon.A09=#Ac.More#
CmLs.ToDoList\8.CMCommon.A10=[]

CmLs.ToDoList\8.CMStyle.T01=#Tm.Customizable_Size#
CmLs.ToDoList\8.CMStyle.T02=

CmLs.ToDoList\8.CMStyle.A01=[!ActivateConfig "#ROOTCONFIG#\ToDoList\8" "CustomizableSize.ini"]
CmLs.ToDoList\8.CMStyle.A02=[]